CREATE TABLE if not exists movies (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    movies_name TEXT NOT NULL,
    movies_price TEXT NOT NULL,
    movies_type TEXT NOT NULL, 
    content TEXT NOT NULL,
    genres_id INTEGER REFERENCES genres(id),
    admin_id INTEGER REFERENCES admin(id)
);
